query GetAnimeList($userName: String) {
  Page(perPage: 1000) {
    mediaList(userName: $userName, type: ANIME) {
      media {
        id
        status
        type
      }
      status
    }
  }
}

query SearchAnimeByName($search: String) {
  Media(type: ANIME, search: $search) {
    id
  }
}

query SearchMangaByName($search: String) {
  Media(type: MANGA, search: $search) {
    id
  }
}
