/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ButtonComponent: typeof import('./components/ButtonComponent.vue')['default']
    GlobalLoader: typeof import('./components/GlobalLoader.vue')['default']
    HeaderComponent: typeof import('./components/HeaderComponent.vue')['default']
    ICarbonDownload: typeof import('~icons/carbon/download')['default']
    ICarbonExport: typeof import('~icons/carbon/export')['default']
    InputField: typeof import('./components/InputField.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToastComponent: typeof import('./components/ToastComponent.vue')['default']
  }
}
